#ifndef CONSTANTS
#define CONSTANTS

#include "Stack.h"

const int OK = 1;
const int CAPACITY_GROWTH = 2;
const int CAPACITY_DECREASE = CAPACITY_GROWTH * 2;
const int STACK_ERRORS_BEGIN = 100;
const StackElem_t STACK_POISON = 77707;
const int N_CANARIES = 2;
const Canary_t CANARY = 144567;

enum ERRORS
    {
    STACK_BAD_STRUCT = STACK_ERRORS_BEGIN + 1,
    STACK_BAD_DATA = STACK_ERRORS_BEGIN + 2, 
    STACK_BAD_SIZE = STACK_ERRORS_BEGIN + 3, 
    STACK_NEGATIVE_SIZE = STACK_ERRORS_BEGIN + 4
    };

#endif //CONSTANTS